spring.application.name=OpstartAfSpringBoot
spring.datasource.url=jdbc:mysql://52.138.181.54:3306/something
spring.datasource.username=root
spring.datasource.password=mypassword
spring.jpa.hibernate.ddl-auto=none

